---
- name: Install Zabbix Server on monitoring
  hosts: monitoring
  become: yes

  tasks:
    - name: Добавить локальный Zabbix-репозиторий
      apt_repository:
        repo: "deb [trusted=yes] http://77.239.101.135/repos/zabbix ./"
        filename: zabbix-local
        state: present

    - name: Обновление apt
      apt:
        update_cache: yes

    - name: Установка PHP и нужных модулей
      apt:
        name:
          - php
          - php-mysql
          - libapache2-mod-php
        state: present


    - name: Установка Zabbix-сервера, фронтенда и MariaDB
      apt:
        name:
          - zabbix-server-mysql
          - zabbix-frontend-php
          - zabbix-agent
          - zabbix-sql-scripts
          - mariadb-server
          - apache2
        state: present

    - name: Установить PyMySQL для Ansible
      apt:
        name: python3-pymysql
        state: present

    - name: Запуск и включение MariaDB
      service:
        name: mariadb
        state: started
        enabled: yes

    - name: Установить пароль для root в MariaDB через сокет от имени mysql
      shell: |
        echo "SET PASSWORD FOR 'root'@'localhost' = PASSWORD('rootpass'); FLUSH PRIVILEGES;" | sudo -u mysql mysql -S /run/mysqld/mysqld.sock
      args:
        creates: /etc/zabbix/.root_password_set

    - name: Отметить, что пароль root установлен
      file:
        path: /etc/zabbix/.root_password_set
        state: touch
    
    - name: Создание базы данных Zabbix
      mysql_db:
        name: zabbix
        state: present
        login_user: root
        login_password: rootpass

    - name: Создание пользователя zabbix
      mysql_user:
        name: zabbix
        password: zabbix
        priv: 'zabbix.*:ALL'
        host: localhost
        state: present
        login_user: root
        login_password: rootpass

    - name: Включить log_bin_trust_function_creators
      mysql_variables:
        variable: log_bin_trust_function_creators
        value: 1
        login_user: root
        login_password: rootpass    
        
    - name: Импорт начальной схемы
      shell: |
        zcat /usr/share/zabbix/sql-scripts/mysql/server.sql.gz | mysql --default-character-set=utf8mb4 -uzabbix -pzabbix zabbix
      args:
        creates: /etc/zabbix/.schema_imported

    - name: Отметить, что импорт схемы выполнен
      file:
        path: /etc/zabbix/.schema_imported
        state: touch

    - name: Отключить log_bin_trust_function_creators
      mysql_variables:
        variable: log_bin_trust_function_creators
        value: 0
        login_user: root
        login_password: rootpass

    - name: Указать пароль в zabbix_server.conf
      lineinfile:
        path: /etc/zabbix/zabbix_server.conf
        regexp: '^#?DBPassword='
        line: 'DBPassword=zabbix'
   
    - name: Создать Apache-конфиг для Zabbix
      copy:
        dest: /etc/apache2/conf-available/zabbix.conf
        content: |
          Alias /zabbix /usr/share/zabbix/ui

          <Directory "/usr/share/zabbix/ui">
              Options FollowSymLinks
              AllowOverride None
              Require all granted
          </Directory>
        owner: root
        group: root
        mode: '0644'

    - name: Включить конфиг Zabbix в Apache
      command: a2enconf zabbix
      args:
        creates: /etc/apache2/conf-enabled/zabbix.conf

    - name: Настройка параметров PHP для Zabbix
      lineinfile:
        path: /etc/php/8.1/apache2/php.ini
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        backrefs: yes
      loop:
        - { regexp: '^post_max_size\s*=.*', line: 'post_max_size = 16M' }
        - { regexp: '^max_execution_time\s*=.*', line: 'max_execution_time = 300' }
        - { regexp: '^max_input_time\s*=.*', line: 'max_input_time = 300' }
      
    - name: Перезапуск служб
      service:
        name: "{{ item }}"
        state: restarted
        enabled: yes
      loop:
        - zabbix-server
        - zabbix-agent
        - apache2
