---
- name: Установить Zabbix-агенты на все хосты, кроме monitoring
  hosts: all:!monitoring
  become: yes

  vars:
    zabbix_server_ip: "{{ hostvars[groups['monitoring'][0]]['inventory_hostname'] }}"

  tasks:
    - name: Добавить локальный Zabbix-репозиторий
      apt_repository:
        repo: "deb [trusted=yes] http://77.239.101.135/repos/zabbix ./"
        filename: zabbix-local
        state: present

    - name: Обновить apt-кэш
      apt:
        update_cache: yes

    - name: Установить Zabbix Agent
      apt:
        name: zabbix-agent
        state: present

    - name: Указать сервер Zabbix
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^Server='
        line: "Server={{ zabbix_server_ip }}"

    - name: Указать активный сервер Zabbix
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^ServerActive='
        line: "ServerActive={{ zabbix_server_ip }}"

    - name: Установить Hostname в конфиге агента
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^Hostname='
        line: "Hostname={{ inventory_hostname }}"

    - name: Запустить и включить Zabbix Agent
      service:
        name: zabbix-agent
        state: restarted
        enabled: yes
