---
- name: Установка и настройка Filebeat на web-серверах
  hosts: web
  become: yes

  vars:
    elasticsearch_host: "http://logging.ru-central1.internal:9200"

  tasks:
    - name: Добавить локальный репозиторий Filebeat
      apt_repository:
        repo: "deb [trusted=yes] http://77.239.101.135/repos/filebeat ./"
        filename: filebeat-local
        state: present

    - name: Обновить apt-кэш
      apt:
        update_cache: yes

    - name: Установить Filebeat
      apt:
        name: filebeat
        state: present

    - name: Включить модули nginx и system
      command: filebeat modules enable nginx system
      args:
        creates: /etc/filebeat/modules.d/nginx.yml

    - name: Настроить Filebeat для отправки в Elasticsearch
      copy:
        dest: /etc/filebeat/filebeat.yml
        content: |
          filebeat.inputs:
            - type: filestream
              id: nginx-access
              paths:
                - /var/log/nginx/access.log
            - type: filestream
              id: nginx-error
              paths:
                - /var/log/nginx/error.log

          output.elasticsearch:
            hosts: ["{{ elasticsearch_host }}"]

          setup.kibana:
            host: "http://kibana.ru-central1.internal:5601"

          setup.dashboards.enabled: true
          setup.ilm.overwrite: true
          setup.ilm.enabled: false
        owner: root
        group: root
        mode: '0644'

    - name: Включить и запустить Filebeat
      service:
        name: filebeat
        state: started
        enabled: yes
